"""add account number

Revision ID: 0238d8953886
Revises: f29053837d8b
Create Date: 2024-03-29 14:48:55.008817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0238d8953886'
down_revision: Union[str, None] = 'f29053837d8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('accountNumber', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_accounts_accountNumber'), 'accounts', ['accountNumber'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_accountNumber'), table_name='accounts')
    op.drop_column('accounts', 'accountNumber')
    # ### end Alembic commands ###
