services:
  server:
    build:
      context: ./backend/
    ports:
      - 8000:8000
    develop:
      watch:
        - action: rebuild
          path: ./backend/
  client:
    build:
      context: ./frontend/
    ports:
      - 3000:80
    develop:
      watch:
        - action: rebuild
          path: ./frontend/